### ISSUE TITLE
PSX Checksum Errors

### ISSUE THREAD

**Issue by BenSanborn** [Koston-0xDEADBEEF/MiSTer-ROMweasel#7]
Hello,

No matter what game I download from PSX, the checksum does not match the meta data file that was just downloaded 1-2 minutes prior.

Mister forum indicates others are seeing this, and it may not be just PSX issue. https://misterfpga.org/viewtopic.php?t=5612&sid=dcdbd3d46104fae7370ca2bcbb015235&start=60

For what its worth, Amiga CD32 did work just now, after failing at PSX.

**Comment by Koston-0xDEADBEEF** [comment]
Sourcing IA_USER/IA_PASS was broken when script was used directly from MiSTer menu. It has been now addressed, can you retry?

**Comment by chloyster** [comment]
I just tried with the latest version to download psx games directly from the mister menu and I am still getting check sum issues

**Comment by Anatrok** [comment]
I have had intermittent issues with CD images (PSX, TG16CD, MCD). from my experience the issue is due to source bandwidth.  I found that using ethernet was more reliable and reattempting download at a later time can be successful.  I have not yet found a file that didn't eventually succeed checksum match.

**Comment by Koston-0xDEADBEEF** [comment]
archive.org has been struggling a lot with bandwidth lately. If a download is interrupted, romweasel can continue from where it left off, but there's not much else we can do about it.

**Comment by Koston-0xDEADBEEF** [comment]
Closing issue due to lack of response. If this becomes relevant again, reply and and I'll re-open it.
